version: '3'

services:
  nvidia_env:
    build:
      context: docker/nvidia
      dockerfile: Dockerfile
    volumes:
      - '.:/work'
    working_dir: /work

  nvidia_hpc_sdk_env:
    build:
      context: docker/nvidia_hpc_sdk
      dockerfile: Dockerfile
    volumes:
      - '.:/work'
    working_dir: /work

  amd_env:
    build:
      context: docker/amd
      dockerfile: Dockerfile
    volumes:
      - '.:/work'
    working_dir: /work
